#pragma once

#define NUMBER_OF_LOGICAL_CORES 12
#define NUMBER_OF_PHYSICAL_CORES 6
#define TOTAL_VIRTUAL_MEMORY 2048
#define AVAILABLE_VIRTUAL_MEMORY 2048
#define TOTAL_PHYSICAL_MEMORY 6218
#define AVAILABLE_PHYSICAL_MEMORY 3860
#define IS_64BIT 1
#define HAS_FPU 1
#define HAS_MMX 1
#define HAS_MMX_PLUS 0
#define HAS_SSE 1
#define HAS_SSE2 1
#define HAS_SSE_FP 0
#define HAS_SSE_MMX 0
#define HAS_AMD_3DNOW 0
#define HAS_AMD_3DNOW_PLUS 0
#define HAS_IA64 0
#define OS_NAME "Linux"
#define OS_RELEASE "5.10.102.1-microsoft-standard-WSL2"
#define OS_VERSION "#1 SMP Wed Mar 2 00:30:59 UTC 2022"
#define OS_PLATFORM "x86_64"
